### ISSUE TITLE
please avoid too generic name for executable

### ISSUE THREAD

**Issue by jonassmedegaard** [rudof-project/rudof#53]
Hi,

Thanks for this quite interesting project!

I am looking into packaging it officially for Debian, and have run into an issue with your choice of naming the binary executable: With your deb package, you provide the executable named as `sx`, which clashes with another binary in Debian (part of the package `lrzsz`). The maybe obvious name `shapes` is taken as well (part of the package `gerris`).

For now, I will use the binary name <del>shapes-sx</del>  `rdfshapes` for my draft packaging work. I hope you will agree to rename the binary as well, so that we will not end up with different names.

One way to check for existing names in Debian is by installing `apt-files`, run `sudo apt-file update` once (or do a regular `apt update` which it hooks into, and then run e.g. `apt-file search bin/sx`

**Comment by jonassmedegaard** [comment]
Hmm, I am changing my mind: I will use the name `rdfshapes` for now.

**Comment by labra** [comment]
Thanks for your interest in packaging it in Debian. It is a pity that `sx`is already taken because I would prefer a short name.

Some possibilities, in order of preference for me, could be:

- `shx`: i like because if is the shortest one and I think is not taken
- `rdfsx`: this one is quite short and also reminds that the tool is about RDF, so I like this one also.
- `rdfshape`: I also like this one because it is a reminder of a sister project that I also maintain: https://rdfshape.weso.es/ and in the future I am planning to move most of the code under the web project to depend on the Rust code. However, I hesitate because people could mistake one for the other.
- `rdfshapes`: I like it, although I am not sure about the extra (s) at the end

**Comment by labra** [comment]
By the way...once we decide the new name, are you going to do a PR or do you prefer me to change it in `Cargo.toml` ?

**Comment by jonassmedegaard** [comment]
Personally, I lean towards shortest-while-descriptive names. That also reduces the risk of the inverse problem of some flying toaster screensaver project getting introduced next month, choosing to use same nonsense-ultrashort name as we now decide on.
I therefore wote for rdfshape. But perhaps I am missing some fun word play with "sx", that I then suggest that you add prominently to the README.md. I was guessing it is an abbreviation of ShEx, and has less connotations for users of your project more interested in SHACL and DCTAP.

As for doing the change, it is by far the easiest that you simply do it: I am into copyleft (ie. GPL licensing instead of the more permissive MIT and Apache-2.0 licenses) and while I have used git since 2009, I've never done a Github PR due to scepticism towards clauses in their Terms of Service.

**Comment by jonassmedegaard** [comment]
if this project is also sensible to reuse as Cargo crates, you might consider renaming the crates as well - and then for consistency the repository itself. When providing both library crates and an executable (and perhaps a daemon too in the future), I find it more sensible that the stem of the repo name is same as for all public lib and bin crates.

**Comment by labra** [comment]
Indeed, now I recall that one of the reasons for not using `rdfshape` was that it was already taken as a repository name by us with the [rdfshape](https://github.com/weso/rdfshape) repo. 

Initially, the project started to implement ShEx in Rust, but we later extended the scope to implement SHACL and now for example I am implementing DCTap with the idea to continue expanding the scope to RDF related tools. 

At this moment, some of my future plans are the following:
- Support for ShEx schemas and SHACL shapes graphs...both for checking and validating RDF data with them
- Support for RDF data...in different flavors, for example, RDF data in Turtle files, but also RDF data behind SPARQL endpoints
- Support for Wikidata and Wikibase knowledge graphs. Implementing [WShEx](https://www.weso.es/WShEx/) in the future and the code that can generate Wikidata subsets from WShEx schemas. The [wdsub](https://github.com/weso/wdsub) tool.
- Support for DCTap and other RDF data modeling languages like [LinkML](https://linkml.io/) or [rdf-config](https://github.com/dbcls/rdf-config)
- Support for generating visualizations and/or HTML views of RDF Data models created in ShEx, SHACL, DCTap, etc.
- Support for conversions between some of those languages...for example, convert between different RDF formats (Turtle, N-Triples, RDF/XML, etc.) and between RDF shapes formats (ShExC, ShExJ, ...) and languages (ShEx to SHACL, SHACL to ShEx, DCTap to ShEx, etc....)

So the idea of `sx` was that the `s` could be seen as a `schema` and the `x` as something generic that could be seen as a symbol for cross-conversion or something like that...maybe that's why `shx` could also make sense where `sh` reminds of shapes, and `x` continues with this idea of conversion...or maybe `rdfsx` would also make sense?

**Comment by jonassmedegaard** [comment]
Yes, `rdfsx` makes great sense to me, then.

Please consider adding a section/paragraph to README.md explaining the meaning of the name.

**Comment by jonassmedegaard** [comment]
I will use `rdfsx` as both source and binary package name, and name of executable binary. Unless you suggest otherwise.

**Comment by labra** [comment]
@jonassmedegaard, Would it be possible to change the name from `rdfsx` to `rdfx` ?

I am asking because the extra `s` in `rdfsx` makes it a bit more difficult to pronounce and to type...and the I think the `rdfx` name is also not taken and probably makes sense with the idea that this is a _generic_ tool about rdf.

**Comment by jonassmedegaard** [comment]
The name "rdfs" is not used by anything else in Debian, if that's what you are asking.

If you are asking for my personal opinion, then I agree that easy-to-pronounce and easy-to-type are good features, but additionally easy-to-remember (and [it seems](https://xkcd.com/936/) I am not alone in that), which I find more important than both the other eases.
I find that using syllables over letters are easier to both remember and pronounce, and tolerate it then being slightly more cumbersome to type.

You cannot be convinced to go with `rdfshape`?
What kind of confusion do you worry will happen? I don't think that a command-line tool nor a Rust library is confused with a website - they are all about same topic - shaping languages for, and the shaping of data in, Ressource Description Framework.

**Comment by jonassmedegaard** [comment]
no, it is not a problem at all for me to rename. And also not a problem technically to rename to `rdfs`, only mentally :-)

**Comment by jonassmedegaard** [comment]
Reason it is easy for me to change name is that my packaging work is still preliminary. When (hopefully soon) I get around to introducing it officially in Debian, it is more cumbersome (but still doable) to rename.
So now is a perfect time from my point of view to rename!

**Comment by labra** [comment]
OK, in that case, I will try these days to find other alternatives. 

I am sorry to insist in this, but I think the name can be important, so I prefer to be 100% convinced of it. 

Another alternative that I am now considering would be: 

`wesi`: I already used that name in an old abandoned project with a similar goal. It comes from "WEb Semantics Interface", where the last `i` is the same as in `cli` and the first 3 letters `wes` are both a reminder of tools useful for web semantics and that the project was born inside the [weso](https://www.weso.es/). In fact, I am happy that a lot of years ago I named `weso` my research group because it is a short and descriptive name that is easy to remember. Could `wesi` be similar? I think it is also not taken...

**Comment by labra** [comment]
Another colleague has suggested me:

`wesx`: indicating that it may be easier to remember, short and keeps the original `sx` name inside.

**Comment by angelip2303** [comment]
I've thinking about the name of the ejecutable and the idea of `weshapes` came to my mind. It is a bit longer than the alternatives that you have mentioned. But, at least, it's easy to remember.

**Comment by labra** [comment]
One problem of `weshapes` is that it is focused on shapes a bit too much and it could constrain the project which at this moment already has features that can be useful to do tasks related with the semantic web in general. 

Another possibility could be `wes` which has only three letters and can be easily remembered as "web semantics". 

Although I initially suggested `wesi`, @angelip2303 indicated me that `wesi` has a meaning in some language according to [the Urban Dictionary](https://www.urbandictionary.com/define.php?term=wesi), so it may not be a good idea.

I was looking for `wes` and I think it has no extra meaning and is also not taken as a command in debian. 

@jonassmedegaard, do you think we could use `wes` instead of `rdfsx`.

**Comment by angelip2303** [comment]
> One problem of `weshapes` is that it is focused on shapes a bit too much and it could constrain the project which at this moment already has features that can be useful to do tasks related with the semantic web in general.
> 
> Another possibility could be `wes` which has only three letters and can be easily remembered as "web semantics".
> 
> Although I initially suggested `wesi`, @angelip2303 indicated me that `wesi` has a meaning in some language according to [the Urban Dictionary](https://www.urbandictionary.com/define.php?term=wesi), so it may not be a good idea.
> 
> I was looking for `wes` and I think it has no extra meaning and is also not taken as a command in debian.
> 
> @jonassmedegaard, do you think we could use `wes` instead of `rdfsx`.

I think that the fact that `wes` can be rewriting with just one hand is "handy" 😉

**Comment by jonassmedegaard** [comment]
I think I have made it pretty clear that I find it bad to use a short non-descriptive name.

Because I find it bad, I am not really enthusiastic about spending time helping you go down that road, by checking your various suggestions on nonsensical names.

Yes, I do understand that calling the project "fzz" means that you can expand it to cover both steering wheels for ships and mouse trapping glue, but that doesn't change my point that "fzz" is a bad name because it is not descriptive.
This is your project, not mine, so feel free to insist on a non-descriptive name. Just bware that downstream users (not only me, on behalf of Debian) may choose to rename your "fzz" to "that-spanish-fzz" or "semantic-rust-fzz". I.e. namespace collision is not the only reason your tool risk renaming downstream - weird choice of name may in itself cause downstreams to turn their back on your choice of name.

I think you should think hard if it really is sensible for a single project to contain a single executable binary serving wildly different purposes.

Would it perhaps make sense to "meet" in a (maybe also video, but most importantly voice) chat? As a very lightweight and very stable service I can recommend to use https://letsmeet.no/ - then we just need to decide on a time (and a name for the chatroom, ha ha ha)

**Comment by labra** [comment]
> What is the scope of this project?
> 
> My impression is that the scope is transforming and validating shapes of RDF data and RDF shaping expressions themselves.
> 

Indeed, thanks for asking it. I have drafted a [scope page](https://github.com/weso/shapes-rs/wiki/%5BADR-04%5D-Scope-of-the-project) where I try to define the scope as I see it now.

> If the answer is that it is a playground for reinventing RDF-related wheels as a way to learn about RDF and Rust, then there is no need to avoid name collision, because then the project is utterly unsuitable for widespread use. My hope is that this project is _mainly_ a widely usable tool, and only in non-main branches may derive into learning experiments. If that sounds sensible, and that for those experiments it is more convenient to type "a" instead of "rdf-shapes validate" then I suggest setting up some bash aliases (either just locally, or perhaps included with the project in a contrib/ directory).

The goal is not to re-invent RDF related tools but to make a tool that is usable by people interested in semantic web data and tasks related with RDF data and RDF data modeling.

**Comment by jonassmedegaard** [comment]
given the pretty broad scope indicated at the [scope page](https://github.com/weso/shapes-rs/wiki/%5BADR-04%5D-Scope-of-the-project), I propose one of these names for the executable binary:
1. rdf-juggler
2. rdf-wrangler
3. rdf-tool

I discourage names like "rdfj" or "rdfw" or "rdft", as those offer less meaning, more mystery.

I do worry that a tool covering that large a scope may become complicated to use (many options and/or cumbersome and unwieldy config files), and that it has a high risk of becoming too difficult to maintain.

I encourage you to consider multiple executable binaries, each with a more narrow scope.
E.g. one command *mainly* for transforming data and models (with only common defaults, no or few options, for fetching/validating/visualizing/serving data or models), with a subcommand for each technique or main format to use, and other commands *mainly* for each of the other subscopes.
Or at least think very hard about on which overarching design principles to follow with the tool - e.g. which subcommands to offer and what to steer using options, non-option arguments, environment variables, config files, etc.

I was recently made aware of the website <https://clig.dev/> and find it an absolutely wonderful read.

**Comment by jonassmedegaard** [comment]
https://clig.dev/#naming :-)

**Comment by jonassmedegaard** [comment]
Hm. That clig website, and the "The Poetics of CLI Command Names" that it references, advices agrees with me on picking a memorable name but not on including the function in the name.

So let me suggest another name, memorable, a play on "RDF" without spelling it out which sounds ugly: **rudolf**

**Comment by jonassmedegaard** [comment]
At least [two](https://github.com/quoll/rudolf) [projects](https://github.com/openbudgets/rudolf) already use rudolf for rdf processing projects. But more unique and still memorable is rodolfo - and arguably even better because a) it is spanish and b) each syllable starts with the letters this projects holds so dear. And the references to the animal with graphs growing out of its head is intact: Rodolfo en Reno :-D

**Comment by labra** [comment]
Ops, it's a pity that `rudolf` is already been used because I liked it a lot. In the case of `rodolfo`, one thing I don't like is that it requires three syllables to be pronounced, at least in Spanish, which makes it a bit more difficult to pronounce. 

Maybe, another possibility could be just `rudof`, I saw that it is a common name in German and I think it is not taken. 

Some further points in favour of `rudof` are that it starts with `ru` as well as `rust` and that it is only 5 letters, making it shorter and easier to type, and I think it is also easy to pronounce and memorize.

**Comment by jonassmedegaard** [comment]
Less common and needs a little getting used to, already before I finished writing a negative post I took a liking to it.
I'm convinced: `rudof` is now my favorite!

Cons: Unusual so may need spelling out the first time you encounter it.
Pros: Other alternatives may also need spelling out (is it "f" or "ph"? "ro..." or "ru..."?), and this one, like no other, achieves saying "r-d-f" in two syllables in a memorable way. And gosh, typing it on a qwerty layout keyboard is smooth (no, not single-hand typing but evenly shifting between left and right hand, as originally intended with the qwerty design).
